type EditedFees @entity(immutable: true) {
  id: Bytes!
  teamFees: BigInt! # uint256
  weeklyGiveawayFees: BigInt! # uint256
  buybackFees: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type EditedTeamMultisig @entity(immutable: true) {
  id: Bytes!
  teamMultisig: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type FeesManagementExecuted @entity(immutable: true) {
  id: Bytes!
  forTeam: BigInt! # uint256
  forWeeklyGiveaway: BigInt! # uint256
  forBuyback: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type FeesTokenAdded @entity(immutable: true) {
  id: Bytes!
  token: Bytes! # address
  taskId: Bytes! # bytes32
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type FeesTokenRemoved @entity(immutable: true) {
  id: Bytes!
  token: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type FeesTokenSwapped @entity(immutable: true) {
  id: Bytes!
  token: Bytes! # address
  amountIn: BigInt! # uint256
  amountOut: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type FlareAuction @entity(immutable: true) {
  id: Bytes!
  user: Bytes! # address
  auctionAmount: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type FlareBuyback @entity(immutable: true) {
  id: Bytes!
  token: Bytes! # address
  amount: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type FlareExecution @entity(immutable: true) {
  id: Bytes!
  user: Bytes! # address
  buybackAmount: BigInt! # uint256
  programAmount: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type GelatoFeesCheck @entity(immutable: true) {
  id: Bytes!
  fees: BigInt! # uint256
  token: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type GelatoTaskCancelFailed @entity(immutable: true) {
  id: Bytes!
  internal_id: Bytes! # bytes32
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type GelatoTaskCanceled @entity(immutable: true) {
  id: Bytes!
  internal_id: Bytes! # bytes32
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type GelatoTaskCreated @entity(immutable: true) {
  id: Bytes!
  internal_id: Bytes! # bytes32
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type OwnershipTransferStarted @entity(immutable: true) {
  id: Bytes!
  previousOwner: Bytes! # address
  newOwner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type OwnershipTransferred @entity(immutable: true) {
  id: Bytes!
  previousOwner: Bytes! # address
  newOwner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type SnatchAuction @entity(immutable: true) {
  id: Bytes!
  user: Bytes! # address
  poolToSteal: Bytes! # address
  auctionAmount: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type SnatchExecution @entity(immutable: true) {
  id: Bytes!
  user: Bytes! # address
  poolToSteal: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type SnatchSteal @entity(immutable: true) {
  id: Bytes!
  user: Bytes! # address
  rewardsPool: Bytes! # address
  rewardsToken: Bytes! # address
  rewardsAmount: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type SwapToWrappedToken @entity(immutable: true) {
  id: Bytes!
  swapToWrappedToken: Boolean! # bool
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type SwapTypeChanged @entity(immutable: true) {
  id: Bytes!

  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type SyncFeesManagement @entity(immutable: true) {
  id: Bytes!
  timestamp: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type SyncFeesStarted @entity(immutable: true) {
  id: Bytes!

  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type TokensBurned @entity(immutable: true) {
  id: Bytes!
  amount: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type WithdrawnNative @entity(immutable: true) {
  id: Bytes!
  to: Bytes! # address
  amount: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type WithdrawnToken @entity(immutable: true) {
  id: Bytes!
  token: Bytes! # address
  to: Bytes! # address
  amount: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
