
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface TransferConstructorInput {
  id: ID;
  from: String;
  to: String;
  tokenId: BigInt;
  log_index: BigInt;
  block_number: BigInt;
  transaction_hash: String;
  timestamp: BigInt;
}
@Entity("Transfer")
export class Transfer extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	from: String

	@Required
	@Column("String")
	to: String

	@Required
	@Column("BigInt")
	tokenId: BigInt

	@Required
	@Column("BigInt")
	log_index: BigInt

	@Required
	@Column("BigInt")
	block_number: BigInt

	@Required
	@Column("String")
	transaction_hash: String

	@Required
	@Column("BigInt")
	timestamp: BigInt
  constructor(data: TransferConstructorInput) {super()}
  
}


const source = ` type Transfer @entity {
    id: ID!
    from: String!
    to: String!
    tokenId: BigInt!
	log_index: BigInt!
	block_number: BigInt!
	transaction_hash: String!
	timestamp: BigInt!
}`
DatabaseSchema.register({
  source,
  entities: {
    "Transfer": Transfer
  }
})
